<?php

declare(strict_types=1);

namespace DockerDns;

final class CaddyProxyAdapter implements ProxyAdapter
{
    public const PROBE_HOST = 'docker-dns-probe.invalid';

    public function filename(): string
    {
        return 'docker-dns.caddy';
    }

    /** @param list<array<string,mixed>> $routes */
    public function render(array $routes): string
    {
        $lines = [
            '# Generated by Docker DNS. Changes will be overwritten.',
            'http://' . self::PROBE_HOST . ' {',
            "\trespond 204",
            '}',
            '',
        ];
        foreach ($routes as $route) {
            $customTls = $route['upstream_scheme'] === 'https' && (!$route['verify_tls'] || $route['tls_server_name'] !== '');
            $target = ($customTls ? '' : $route['upstream_scheme'] . '://') . $route['upstream_host'] . ':' . $route['upstream_port'];
            $lines[] = 'http://' . $route['hostname'] . ' {';
            $lines[] = "\treverse_proxy " . $target . ' {';
            $lines[] = "\t\theader_up Host {http.request.host}";
            if ($customTls) {
                $lines[] = "\t\ttransport http {";
                $lines[] = "\t\t\ttls";
                if (!$route['verify_tls']) $lines[] = "\t\t\ttls_insecure_skip_verify";
                if ($route['tls_server_name'] !== '') $lines[] = "\t\t\ttls_server_name " . $route['tls_server_name'];
                $lines[] = "\t\t}";
            }
            $lines[] = "\t}";
            $lines[] = '}';
            $lines[] = '';
        }
        return implode("\n", $lines) . "\n";
    }

    public function validateAndReload(DockerRunner $docker, array $settings, string $containerPath): void
    {
        $container = (string)$settings['proxy_container'];
        $main = (string)($settings['caddy_main_config'] ?? '/etc/caddy/Caddyfile');
        $docker->exec($container, ['caddy', 'validate', '--config', $main, '--adapter', 'caddyfile']);
        $docker->exec($container, ['caddy', 'reload', '--config', $main, '--adapter', 'caddyfile']);
    }

    public function expectedProbeStatus(): int
    {
        return 204;
    }
}
