<?php

declare(strict_types=1);

namespace DockerDns;

final class TraefikProxyAdapter implements ProxyAdapter
{
    public function filename(): string
    {
        return 'docker-dns.yml';
    }

    /** @param list<array<string,mixed>> $routes */
    public function render(array $routes): string
    {
        $entrypoint = 'web';
        $routers = [
            '  routers:',
            '    docker-dns-probe:',
            '      rule: "Host(`docker-dns-probe.invalid`)"',
            '      entryPoints: ["' . $entrypoint . '"]',
            '      service: docker-dns-probe',
        ];
        $services = [
            '  services:',
            '    docker-dns-probe:',
            '      loadBalancer:',
            '        servers:',
            '          - url: "http://127.0.0.1:1"',
        ];
        $transports = [];
        foreach ($routes as $index => $route) {
            $id = 'docker-dns-' . substr(hash('sha256', (string)$route['hostname']), 0, 12);
            $routers[] = '    ' . $id . ':';
            $routers[] = '      rule: "Host(`' . $route['hostname'] . '`)"';
            $routers[] = '      entryPoints: ["' . $entrypoint . '"]';
            $routers[] = '      service: ' . $id;
            $services[] = '    ' . $id . ':';
            $services[] = '      loadBalancer:';
            $services[] = '        passHostHeader: true';
            $services[] = '        servers:';
            $services[] = '          - url: "' . $route['upstream_scheme'] . '://' . $route['upstream_host'] . ':' . $route['upstream_port'] . '"';
            if ($route['upstream_scheme'] === 'https' && (!$route['verify_tls'] || $route['tls_server_name'] !== '')) {
                $transport = $id . '-transport';
                $services[] = '        serversTransport: ' . $transport;
                $transports[] = '    ' . $transport . ':';
                if (!$route['verify_tls']) $transports[] = '      insecureSkipVerify: true';
                if ($route['tls_server_name'] !== '') $transports[] = '      serverName: "' . $route['tls_server_name'] . '"';
            }
        }
        $lines = ['# Generated by Docker DNS. Changes will be overwritten.', 'http:'];
        $lines = array_merge($lines, $routers, $services);
        if ($transports !== []) {
            $lines[] = '  serversTransports:';
            $lines = array_merge($lines, $transports);
        }
        return implode("\n", $lines) . "\n";
    }

    public function validateAndReload(DockerRunner $docker, array $settings, string $containerPath): void
    {
        // Traefik's file provider watches the mounted parent directory and hot-reloads this file.
        usleep(2500000);
    }

    public function expectedProbeStatus(): int
    {
        return 502;
    }
}
